### CDV-SLAM Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 96
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 13

# threshold for keyframe removal
KEYFRAME_THRESH: 15.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: True

CENTROID_SEL_STRAT: 'SCORE'
CENTROID_SAMPLE_STRAT: 'UPPERLEFT'

LOOP_CLOSURE: False
CLASSIC_LOOP_CLOSURE: False

FILTER_DYNAMIC_CLASS: True
SEG_HEAD: 'dinov2_vits14_ade20k_linear_headflatten.pth'
DEPTH_HEAD: 'dinov2_vits14_kitti_linear_headflatten.pth'